car_service/car_service/urls.py
from django.contrib import admin
from django.urls import path, include



admin.site.site_header = 'Service administration'
admin.site.site_title = 'Service administration'
admin.site.index_title = 'Applications administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.web_app.urls')),
    path('service/', include('apps.service_app.urls')),
    path('account/', include('apps.auth_app.urls')),
    path('api/', include('apps.api_app.urls')),
]


handler404 = 'apps.web_app.views.custom_404'
# handler500 = 'apps.web_app.views.custom_500'

car_service/apps/service_app/models.py
from django.db import models
from ..web_app.models import CustomerProfile
from django.contrib.auth import get_user_model

UserModel = get_user_model()


class EmployeesProfile(models.Model):
    MAX_LENGTH_NAMES = 20
    MAX_PHONE_LENGTH = 14
    
    
    first_name = models.CharField(
        max_length=MAX_LENGTH_NAMES,
    )
    last_name = models.CharField(
        max_length=MAX_LENGTH_NAMES,
    )
    email = models.EmailField(
        
    )
    phone = models.CharField(
        max_length=MAX_PHONE_LENGTH,
    )
    
    user_id = models.OneToOneField(
        UserModel,
        primary_key=True,
        on_delete=models.CASCADE,
        limit_choices_to={'is_customer': False},
    )
    
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    
class CarBrand(models.Model):
    MAX_LENGTH_BRAND = 25
    MAX_LENGTH_IMAGE = 50
    
    
    id = models.AutoField(
        primary_key=True
    )
    brand = models.CharField(
        max_length=MAX_LENGTH_BRAND,
    )
    image = models.CharField(
        max_length=MAX_LENGTH_IMAGE,
        
    )
    
    
    def get_image(self):
        return self.image
    
    def __str__(self):
        return self.brand
    
    
class ServiceGallery(models.Model):
    MAX_LENGTH_IMAGE = 50
    
    image = models.CharField(
        max_length=MAX_LENGTH_IMAGE,
    )
    
class Cars(models.Model):
    MAX_LENGTH_MODEL = 10
    MAX_LENGTH_VIN = 30
    MAX_LENGTH_KILOMETERS = 8
    MAX_LENGTH_REGISTER_NUMBER =12
    
    brand = models.ForeignKey(
        CarBrand,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    
    model = models.CharField(
        max_length=MAX_LENGTH_MODEL,
    )
    year = models.DateField()
    VIN = models.CharField(
        max_length=MAX_LENGTH_VIN,
    )
    repair = models.BooleanField(
        default=False,
    )
    kilometers = models.CharField(
        null=True,
        blank=True,
        max_length=MAX_LENGTH_KILOMETERS,
    )
    
    registration_number = models.CharField(
        null=True,
        blank=True,
        unique=True,
        max_length=MAX_LENGTH_REGISTER_NUMBER,
    )
    have_history= models.BooleanField(
        default=False,
    )
    
    user_id = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,

    )
    
    def __str__(self):
        return f"{self.brand} - {self.registration_number}"

    
class RepairHistory(models.Model):
    def default_json():
        return  {
            "Date": "", 
            "Kilometers": "",
            "Changed parts": {
                
            }
        }
        
    car_id = models.ForeignKey(
        Cars,
        on_delete=models.CASCADE,        

    )
    history = models.JSONField(
        default=default_json
    )
    
    

class CarQueue(models.Model):
    TYPE_STATUS = (
        ('Awaiting To Take', 'Awaiting To Take'),
        ('Investigating Car', 'Investigating Car'),
        ('In Progress', 'In Progress'),
        ('Done', 'Done'),
        
    )
    car_id = models.OneToOneField(
        Cars,
        primary_key=True,
        on_delete=models.CASCADE,
        verbose_name="Customer Car",
        

    )
    
    mechanic_id = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="Mechanic",
    )
    
    status = models.CharField(
        choices=TYPE_STATUS,
        max_length=20,
        null=True,
        blank=True,
    )
    
    
    def get_choices(self):
       return [choice[0] for choice in self.TYPE_STATUS]

car_service/templates/service/add-car-queue.html
{% extends 'service/base.html' %}

{% block main %}
    <form class="adding__from" action="{% url 'add car in queue' car_pk %}" method="POST">
        <h2>Move to Queue Form</h2>
        {% for field in queue_from %}
            <div class="form-control">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
        {% csrf_token %}
        <button>Save</button>
    </form>
{% endblock  %}
    

car_service/templates/service/add-car.html
{% extends 'service/base.html' %}

{% block main %}
    <form class="adding__from" method="POST" action="{% url 'add car page' %}">
        <h2>Add Car Form</h2>
        {% if form.errors %}
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
        {% endif %}

        {% for field in form %}
            <div class="form-control">
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
        {% csrf_token %}
        <button>Add Car</button>
    </form>
{% endblock  %}

car_service/templates/service/add-customer.html
{% extends 'service/base.html' %}

{% block main %}
    <form class="adding__from" method="POST" action="{% url 'add customer page' %}">
        <h2>Create Customer From</h2>
        {% if form.errors %}
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
        {% endif %}
        {% for field in form %}
            <div class="form-control">
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
        {% csrf_token %}
        <button>Add customer</button>
    </form>
{% endblock  %}

car_service/templates/service/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service</title>
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/service/service_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/service/service.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

</head>
<body>
    
    <header class="header">
        <a href="{% url 'service home page' %}"><img src="{% static 'images/logo.png' %}" alt="Logo img"  class="logo"></a>

        <div class="auth_system">
            <ul>
                <li class="profile">
                    <img src="{% static 'images/user.png' %}" alt="user img" class="navigation__icons">
                    <ul class="profile-settings">
                        <li class="profile-settings-row"><a href="{% url 'employee profile' user.pk %}">Profile</a></li>
                        {% if user.is_authenticated %}
                            <li class="profile-settings-row"><a href="{% url 'logout' %}">Logout</a></li>
                        {% endif %}
                        
                    </ul>
                </li>
       
            </ul>
        </div>
    </header>

    <aside class="sidenav open">
        <div class="sidebar-header">
            <a href="#" class="toggle-sidebar" onclick= "closeSideBar();">
              <i class="fas fa-chevron-left"></i>
            </a>
        </div>
        <nav class="navitaion" >
            <ul>
                {% if perms.service_app.add_cars or  user.is_superuser %}
                    <li><a href="{% url 'car queue' %}" onClick="updateStatus();"><img src="{% static 'images/car_queue.png' %}" alt="car_queue img" class="navigation__icons"></a></li>
                    <li><a href="{% url 'cars' %}"><img src="{% static 'images/cars.png' %}" alt="cars img" class="navigation__icons"></a></li>
                    <li><a href="{% url 'customers page' %}"><img src="{% static 'images/customers.png' %}" alt="customer img" class="navigation__icons"></a></li>
                {% else %}
                    <li><a href="{% url 'car queue' %}"><img src="{% static 'images/car_queue.png' %}" alt="car_queue img" class="navigation__icons"></a></li>
                {% endif %}
            </ul>
        </nav>
    </aside>
   
    <main class="main">
        {% block main %}
        {% endblock  %}
    </main>

{% block script %}
{% endblock  %}
{% block script_sidenav %}
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function() {

            closeSideBar = () => {
                const sidebar = document.querySelector('.sidenav');
                const arrow = document.querySelector('.fa-chevron-left');
                
                if (sidebar.className.includes("open")) {
                    sidebar.classList.remove('open');
                    sidebar.classList.add("close");
                    arrow.style.transform = "rotate(180deg)"
                    
                }
                else {
                    sidebar.classList.remove('close');
                    sidebar.classList.add("open");
                    arrow.style.transform = "rotate(360deg)"
                    
                }
                
            };
        });
    </script>
{% endblock  %}
</body>
</html>

car_service/templates/service/car-history.html
{% extends 'service/base.html' %}

{% block main %}
    <form class="adding__from" method="POST" action="{% url 'add car history' car_pk %}">
        <h2>Car history From</h2>
        <div class="form-control">
            <lable for="kilometers" >Kilometers:</lable>
            <input placeholder="100 000" id="kilometers" name="kilometers" required></input>
        </div>
        <div class="form-control part">
            <h4 class="part_title" for="parts">Parts</h4>

            <ul class="list_parts">
            </ul>

            <div class="inputs">
                <input type="text" placeholder="Enter name" >
                <input type="text" placeholder="Enter QTY" >
                <input type="text" placeholder="Enter Price" >
                <input type="button" class="add_in_list" value='Add'>
            </div>
            <ul class="parts_btn">
                <li><a class="add_part_btn">Add part</a></li>
                <li><a class="delete_part_btn">Delete part</a></li>
            </ul>
        </div>
        {% csrf_token %}
        <button>Add history</button>
    </form>

{% endblock %}

{% block script %}
    <script>
        window.onload = () => {
            let partsCounter = 0
            const addBtn = document.querySelector('.add_part_btn');
            const deleteBtn = document.querySelector('.delete_part_btn');
            const partsList = document.querySelector('.list_parts');


            addBtn.addEventListener('click', showInputFields);
            deleteBtn.addEventListener('click', deletePart);
        
            partsList.addEventListener('click', function(event) {
                const selectedLi = event.target;
                if (selectedLi.className === 'part_label') {
                    selectedLi.parentElement.classList.toggle('selected');
                }
            });
            
            
            function showInputFields() {
                const inputs = document.querySelector('.inputs');
                inputs.style.display = 'flex';
            }

            function deletePart() {
                const selectedItems = document.querySelectorAll('.selected');
                
                partsCounter -= selectedItems.length;

                selectedItems.forEach(item => {
                    partsList.removeChild(item);
                }); 
            }

            document.querySelector('.add_in_list').addEventListener('click', function() {
                const inputs = document.querySelector('.inputs');
                const partsList = document.querySelector('.list_parts');
            
                let part = '';
            
                for (let index = 0; index < inputs.children.length - 1; index++) {
                    part += inputs.children[index].value

                    if (index < inputs.children.length - 2) {
                        part += ` - `;
                    }

                    inputs.children[index].value = '';
                }

                partsCounter += 1
                
                if (part.trim() !== '') {
                    const newLi = document.createElement('li');
                    newLi.innerHTML = `
                    <label for="part${partsCounter}" class='part_label'>${part}</label>
                    <input type="hidden" value='${part.trim()}' id='part${partsCounter}' name="part${partsCounter}" readonly="readonly" class="part_inputs"></input>
                    `;
                    partsList.appendChild(newLi);
                }
                
                inputs.style.display = 'none';
            });
        };
    </script>
{% endblock  %}

car_service/templates/service/car_queue.html
{% extends 'service/base.html' %}

{% block main %}
    <h1>Car Queue</h1>
    <section class="container-table">
        <form id="form" method='POST' action="{% url 'car queue' %}">
            {% csrf_token %}
            <table class="cars">
                <tr>
                    <th>Model</th>
                    <th>Registration Number</th>
                    <th>Status</th>
                    <th>Assigne</th>
                </tr>
                {% for car in queue %}
                    <tr id="{{ car.pk }}">
                        <td>{{ car.car_id.model }}</td>
                        <td>{{ car.car_id.registration_number }}</td>
                        <td>
                            <select id='choice' class="choice__filed">
                                {% for choice in car.get_choices %}
                                    {% if choice != car.status %}
                                        <option value="{{ choice }}">{{ choice }}</option>
                                    {% else %}
                                        <option value="{{ choice }}" selected>{{ choice }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </td>
                        <td>{{ car.mechanic_id }}</td>
                    </tr>
                    
                {% endfor %}
            </table>
            <input type="hidden" value="" name="submitter"  id="submitter"></input>
        </form>
        <section class="pages">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}&search={{ search }}"><i class="fas fa-step-backward"></i></a>
            {% else %}
                <a><i class="fas fa-step-backward"></i></a>
            {% endif %}

            {{ page_obj.number }} / {{ paginator.num_pages }}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&search={{ search }}"><i class="fas fa-step-forward"></i></a>
            {% else %}
                <a><i class="fas fa-step-forward"></i></a>
            {% endif %}
        </section>
    </section>
{% endblock  %}

{% block script %}
<script>
    window.onload = () => {
        var mySelect = document.getElementById('choice');
        mySelect.onchange = (event) => {
            var pk = event.target.parentNode.parentNode;
            subbmiter = document.getElementById('submitter');
            subbmiter.value = [pk.id, event.target.value]
            document.getElementById("form").submit(); 
        } 
    }
</script>
{% endblock  %}

car_service/templates/service/cars.html
{% extends 'service/base.html' %}

{% block main %}
    <h1>Cars</h1>
    <section class="container-table">
        <div class="service__btn__add">
            <a href="{% url 'add car page' %}" class="btn__action service_add">Add car</a>
            <form action="{% url 'cars' %}"> 
                <input placeholder="search register number" type="text" name="search"/>
                <input type="submit" value="search"/>
            </form>
        </div>
            <table class="cars">
                <tr>
                    <th class="sort" onclick="sortBy(0)" >Model</th>
                    <th class="sort" onclick="sortBy(0)" >Registration Number</th>
                    <th class="sort" onclick="sortBy(0)" >VIN</th>
                    <th class="sort" onclick="sortBy(0)" >Customer</th>
                    <th>Actions</th>
                </tr>
                {% for car in cars %}
                    <tr id="{{ car.pk }}">
                        <td>{{ car.model }}</td>
                        <td>{{ car.registration_number }}</td>
                        <td>{{ car.VIN }}</td>
                        <td>{{ car.user_id }}</td>
                        <td>
                            <a class="btn__action details" onClick='carDetail("{% url "car" car.pk %}")'>Detail</a>
                            <a class="btn__action delete" onClick='deleteCar("{% url "car" car.pk %}")'>Delete</a>
                            {% if car_done %}
                                {% for done in car_done %}
                                    {% if done.status == "Done" and done.car_id.pk == car.pk %}
                                        <a class="btn__action history" href="{% url 'add car history' car.pk %}">Fill History</a>
                                    {% else %}
                                        <a class="btn__action move" href="{% url 'add car in queue' car.pk %}">Move to Repair</a>
                                    {% endif %} 
                                {% endfor %}
                            {% elif not car.repair %}
                                <a class="btn__action move" href="{% url 'add car in queue' car.pk %}">Move to Repair</a>
                            {% endif %}
                        </td>

                    </tr>
                    
                {% endfor %}
            </table>
            
            <section class="pages">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}&search={{ search }}"><i class="fas fa-step-backward"></i></a>
                {% else %}
                    <a><i class="fas fa-step-backward"></i></a>
                {% endif %}
    
                {{ page_obj.number }} / {{ paginator.num_pages }}
    
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}&search={{ search }}"><i class="fas fa-step-forward"></i></a>
                {% else %}
                    <a><i class="fas fa-step-forward"></i></a>
                {% endif %}
            </section>
    </section>

    <section id="popup1" class="overlay">
        <div class="adding__from">
            <div class="content">       
            </div>
        </div>
    </section>

{% endblock  %}
{% block script %}
<script type="text/javascript">
    cPrev = -1; 

    deleteCar = (url) => {
        fetch(url, {
            method: 'DELETE',
        })
        .then(response => {
            if (response.ok) {
                location.href = "{% url 'cars' %}";
            }
        }
        
        )
        .catch(function(err) {
            console.info(err + " url: " + url);
        });
    }


    const getCarDetails = (url) => 
        fetch(url).then(
                data => data.json()
            )

    saveDate = (url) => {
        const formFilled =  document.querySelectorAll(".form-control input")

        const formData = {
            'model': formFilled[0].value,
            'year': formFilled[1].value,
            'VIN': formFilled[2].value,
            'kilometers': formFilled[3].value,
        }
        
        fetch(url,{
            method: 'PUT',
            headers: {
                "Content-Type": "application/json",
                },
            body: JSON.stringify(formData)
        })
        .then(response => {
            const form = document.querySelector(".form-control")
            const formInputs = document.querySelector(".form__inputs")
            const spanMessage = document.createElement("span")
            
            if (response.ok){
                
                spanMessage.textContent = "Save was success"
                spanMessage.style.cssText = `
                    display: block;
                    text-align: center;
                    color: green;
                    margin: 20px;
                
                `

            }
            else {
                spanMessage.textContent = "Save was not success"
                spanMessage.style.cssText = `
                    display: block;
                    text-align: center;
                    color: red;
                    margin: 20px;
                
                `

            }
            form.insertBefore(spanMessage, formInputs)
        }
        )
        .catch(function(err) {
            console.info(err + " url: " + url);
        });


    }


    carDetail = (url) => {
        const id = url.split('/')[4];
        const contentBox = document.getElementsByClassName("content")[0]
        const popup = document.getElementsByClassName("overlay")[0]
        contentBox.innerHTML = ""
        const details = document.createElement("section")

        getCarDetails(url).then(
            data => 
            details.innerHTML = `
                <div class="form-control">
                    <h2>Car Detail</h2>
                    <div class="form__inputs">
                        <label>Model</label>
                        <input type="text" value="${data.model}"></input>
                        <label>Year</label>
                        <input type="text" value="${data.year}"></input>
                        <label>VIN</label>
                        <input type="text" value="${data.VIN}"></input>
                        <label>Kilometers</label>
                        <input type="text" value="${data.kilometers}"></input>
                        <button onClick="saveDate('${url}');">Save</button>
                        <button onClick="closePopUp();">Back</button>
                    </div>
                </div>
            `

            
        )

        contentBox.appendChild(details)

        popup.style.cssText = `
            display: block;
        `;

    }

    closePopUp = () => {
        const popup = document.getElementsByClassName("overlay")[0]

        popup.style.cssText = `
            display: none;
        `;
    }

    function sortBy(c, row) {

        rows = document.querySelector(".cars").rows.length;
        columns = document.querySelector(".cars").rows[0].cells.length; 
        arrTable = [...Array(rows)].map(e => Array(columns));
        for (ro=0; ro<rows; ro++) {
            for (co=0; co<columns; co++) {
      
                arrTable[ro][co] = document.querySelector(".cars").rows[ro].cells[co].innerHTML;
            }
        }

        th = arrTable.shift();
        
        if (c !== cPrev) {
            arrTable.sort(
                function (a, b) {
                    if (a[c] === b[c]) {
                        return 0;
                    } else {
                        return (a[c] < b[c]) ? -1 : 1;
                    }
                }
            );
        } else {
            arrTable.reverse();
        }
        
        cPrev = c; 

        arrTable.unshift(th);


        for (ro=0; ro<rows; ro++) {
            for (co=0; co<columns; co++) {
                document.querySelector(".cars").rows[ro].cells[co].innerHTML = arrTable[ro][co];
            }
        }
    }

</script>
{% endblock  %}

car_service/templates/service/customers.html
{% extends 'service/base.html' %}

{% block main %}
<h1>Customers</h1>
    <section class="container-table">
        <div class="service__btn__add">
            <a href="{% url 'add customer page' %}" class="btn__action service_add">Add customer</a>
            <form action="{% url 'customers page' %}"> 
                <input placeholder="search customer" type="text" name="search"/>
                <input type="submit" value="search"/>
            </form>
        </div>
    {% if customers %}

            <table class="customer">
                <tr>
                    <th class="sort" onclick="sortBy(0)">Username</th>
                    <th class="sort" onclick="sortBy(0)">First name</th>
                    <th class="sort" onclick="sortBy(0)">Last name</th>
                    <th class="sort" onclick="sortBy(0)">Email</th>
                    <th>Phone</i></th>
                    <th>Actions</i></th>

                </tr>
                {% for customer in customers %}
                    <tr id="{{ customer.pk }}">
                        <td>{{ customer.user_id }}</td>
                        <td>{{ customer.first_name }}</td>
                        <td>{{ customer.last_name }}</td>
                        <td>{{ customer.email }}</td>
                        <td>{{ customer.phone }}</td>

                        <td>
                            <a class="btn__action details" onClick='customerDetail("{% url "customers" customer.pk %}")'>Detail</a>
                            <a class="btn__action delete" onClick='deleteCusotmer("{% url "customers" customer.pk %}")'>Delete</a>
                        </td>

                    </tr>
                    
                {% endfor %}
            </table>
            <section class="pages">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}&search={{ search }}"><i class="fas fa-step-backward"></i></a>
                {% else %}
                    <a><i class="fas fa-step-backward"></i></a>
                {% endif %}
    
                {{ page_obj.number }} / {{ paginator.num_pages }}
    
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}&search={{ search }}"><i class="fas fa-step-forward"></i></a>
                {% else %}
                    <a><i class="fas fa-step-forward"></i></a>
                {% endif %}
            </section>
    </section>
{% else %}
    <h2>There no customer</h2>
{% endif %}

    <section id="popup1" class="overlay">
        <div class="adding__from">
            <div class="content">       
            </div>
        </div>
    </section>

{% block script %}
<script type="text/javascript">
    cPrev = -1; 

    deleteCusotmer = (url) => {
        fetch(url, {
            method: 'DELETE',
        })
        .then(response => {
            if (response.ok) {
                location.href = "{% url 'customers page' %}";
            }
        }
        
        )
        .catch(function(err) {
            console.info(err + " url: " + url);
        });
    }
        

    saveDate = (url) => {
        const formFilled =  document.querySelectorAll(".form-control input")
        pk = url.split("/")[3]

        const formData = {
            'user_id': pk,
            'first_name': formFilled[0].value,
            'last_name': formFilled[1].value,
            'email': formFilled[2].value,
            'phone': formFilled[3].value,
        }
        
        fetch(url,{
            method: 'PUT',
            headers: {
                "Content-Type": "application/json",
                },
            body: JSON.stringify(formData)
        })
        .then(response => {
            const form = document.querySelector(".form-control")
            const formInputs = document.querySelector(".form__inputs")
            const spanMessage = document.createElement("span")
            
            if (response.ok){
                spanMessage.textContent = "Save was success"
                spanMessage.style.cssText = `
                    display: block;
                    text-align: center;
                    color: green;
                    margin: 20px;
                
                `

            }
            else {
                spanMessage.textContent = "Save was not success"
                spanMessage.style.cssText = `
                    display: block;
                    text-align: center;
                    color: red;
                    margin: 20px;
                
                `

            }
            form.insertBefore(spanMessage, formInputs)

            setTimeout(() => spanMessage.remove(), 5000)
        }
        )
        .catch(function(err) {
            console.info(err + " url: " + url);
        });


    }


    customerDetail = (url) => {
        const id = url.split('/')[4];
        const contentBox = document.getElementsByClassName("content")[0]
        const popup = document.getElementsByClassName("overlay")[0]
        contentBox.innerHTML = ""
        const details = document.createElement("section")

        fetch(url)
            .then(
                data => data.json()
            )
            .then(

            data =>
            
            details.innerHTML = `
                <div class="form-control">
                    <h2>Car Detail</h2>
                    <div class="form__inputs">
                        <label>First name</label>
                        <input type="text" value="${data.first_name}"></input>
                        <label>Last name</label>
                        <input type="text" value="${data.last_name}"></input>
                        <label>Email</label>
                        <input type="text" value="${data.email}"></input>
                        <label>Phone</label>
                        <input type="text" value="${data.phone}"></input>
                        <button onClick="saveDate('${url}');">Save</button>
                        <button onClick="closePopUp();">Back</button>
                    </div>
                </div>
            `
           
        )

        contentBox.appendChild(details)

        popup.style.cssText = `
            display: block;
        `;

    }

    closePopUp = () => {
        const popup = document.getElementsByClassName("overlay")[0]

        popup.style.cssText = `
            display: none;
        `;
        location.reload();
    }



    function sortBy(c, row) {

        rows = document.querySelector(".customer").rows.length;
        columns = document.querySelector(".customer").rows[0].cells.length; 
        arrTable = [...Array(rows)].map(e => Array(columns));
        for (ro=0; ro<rows; ro++) {
            for (co=0; co<columns; co++) {
      
                arrTable[ro][co] = document.querySelector(".customer").rows[ro].cells[co].innerHTML;
            }
        }

        th = arrTable.shift();
        
        if (c !== cPrev) {
            arrTable.sort(
                function (a, b) {
                    if (a[c] === b[c]) {
                        return 0;
                    } else {
                        return (a[c] < b[c]) ? -1 : 1;
                    }
                }
            );
        } else {
            arrTable.reverse();
        }
        
        cPrev = c; 

        arrTable.unshift(th);


        for (ro=0; ro<rows; ro++) {
            for (co=0; co<columns; co++) {
                document.querySelector(".customer").rows[ro].cells[co].innerHTML = arrTable[ro][co];
            }
        }
    }
</script>
{% endblock  %}
{% endblock  %}